# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/frum-repo',
                'doc_host': 'https://AL42Gaming.github.io',
                'git_url': 'https://github.com/AL42Gaming/frum-repo',
                'lib_path': 'frum_repo'},
  'syms': { 'frum_repo.MoEgraph': {'frum_repo.MoEgraph.foo': ('moegraph.html#foo', 'frum_repo/MoEgraph.py')},
            'frum_repo.core': {'frum_repo.core.foo': ('moegraph.html#foo', 'frum_repo/core.py')}}}
